### ISSUE TITLE
Obsolete build syntax in build.gradle file.

### ISSUE THREAD

**Issue by Dheeraj1998** [apuder/Highlight#1]
Hi!

The _build.gradle_ file contains some obsolete syntax for the compilation of the different parts of the Android application. If you are willing, I would like to love to submit a PR to update them to latest syntax versions.

Thanks.

Regards,
Dheeraj Nair

**Comment by apuder** [comment]
PRs are always welcome! :)

**Comment by Dheeraj1998** [comment]
#2 The issue has been resolved in this pull request. Have a look at it 😄
